version: '3.8'

services:
  # MongoDB Service
  mongodb:
    image: mongo:latest
    container_name: mongodb
    restart: always
    ports:
      - "27017:27017"
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=admin123

  # sportsbookDataService Service
  sportsbookdataservice:
    build:
      context: ./sportsbookDataService
    container_name: sportsbookDataService
    ports:
      - "8080:8080"
    depends_on:
      - mongodb  # Wait for MongoDB to start before this service

  # sportsbookRetrievingService Service
  sportsbookretrievingservice:
    build:
      context: ./sportsbookRetrievingService
    container_name: sportsbookRetrievingService
    ports:
      - "8081:8080"
    depends_on:
      - mongodb
      - sportsbookdataservice